/* eslint-env node */

const webpack = require("webpack");
const path = require("path");

const CleanWebpackPlugin = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  mode: "none",
  entry: {
    app: path.resolve(__dirname, "src/index.ts")
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "[name].js"
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loaders: ["awesome-typescript-loader"],
        exclude: path.resolve(__dirname, "node_modules"),
        include: path.resolve(__dirname, "src")
      },
      {
        test: /\.css$/,
        use: [
          { loader: "style-loader" },
          {
            loader: "typings-for-css-modules-loader",
            options: {
              banner:
                "// This file is automatically generated by typings-for-css-modules.\n// Please do not change this file!",
              //css-loader options
              modules: true,
              localIdentName: "[local]__[hash:base64:5]",
              importLoaders: 1
            }
          }
        ]
      }
    ]
  },

  plugins: [new CleanWebpackPlugin(["dist"]), new HtmlWebpackPlugin(),
  new webpack.WatchIgnorePlugin([
      /css\.d\.ts$/, // ignore *.d.ts files
  ]),]
};
