// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IStylesCss {
  'app': string;
  'app--blue': string;
}

export const locals: IStylesCss;
export default locals;
